class FieldCountryUs extends HTMLElement {

  constructor() {
      super();

      Ext.create('Ext.data.Store', {
        autoLoad: true,
          fields: [ 'name', 'value' ],
          data: [
              { "value":"UNITED STATES", "name":"UNITED STATES" },
              { "value":"CANADA", "name":"CANADA" },
              { "value":"UNITED KINGDOM", "name":"UNITED KINGDOM" },
              { "value":"GERMANY", "name":"GERMANY" },
              { "value":"FRANCE", "name":"FRANCE" },
              { "value":"NETHERLANDS", "name":"NETHERLANDS" },
              { "value":"SWEDEN", "name":"SWEDEN" },
              { "value":"SWITZERLAND", "name":"SWITZERLAND" },
              { "value":"JAPAN", "name":"JAPAN" },
              { "value":"SOUTH KOREA", "name":"SOUTH KOREA" },
              { "value":"AUSTRALIA", "name":"AUSTRALIA" },
              { "value":"AFGHANISTAN", "name":"AFGHANISTAN" },
              { "value":"ALAND ISLANDS", "name":"ALAND ISLANDS" },
              { "value":"ALBANIA", "name":"ALBANIA" },
              { "value":"ALGERIA", "name":"ALGERIA" },
              { "value":"AMERICAN SAMOA", "name":"AMERICAN SAMOA" },
              { "value":"ANDORRA", "name":"ANDORRA" },
              { "value":"ANGOLA", "name":"ANGOLA" },
              { "value":"ANGUILLA", "name":"ANGUILLA" },
              { "value":"ANTARCTICA", "name":"ANTARCTICA" },
              { "value":"ANTIGUA AND BARBUDA", "name":"ANTIGUA AND BARBUDA" },
              { "value":"ARGENTINA", "name":"ARGENTINA" },
              { "value":"ARMENIA", "name":"ARMENIA" },
              { "value":"ARUBA", "name":"ARUBA" },
              { "value":"AUSTRIA", "name":"AUSTRIA" },
              { "value":"AZERBAIJAN", "name":"AZERBAIJAN" },
              { "value":"BAHAMAS", "name":"BAHAMAS" },
              { "value":"BAHRAIN", "name":"BAHRAIN" },
              { "value":"BANGLADESH", "name":"BANGLADESH" },
              { "value":"BARBADOS", "name":"BARBADOS" },
              { "value":"BELARUS", "name":"BELARUS" },
              { "value":"BELGIUM", "name":"BELGIUM" },
              { "value":"BELIZE", "name":"BELIZE" },
              { "value":"BENIN", "name":"BENIN" },
              { "value":"BERMUDA", "name":"BERMUDA" },
              { "value":"BHUTAN", "name":"BHUTAN" },
              { "value":"BOLIVIA", "name":"BOLIVIA" },
              { "value":"BOSNIA AND HERZEGOVINA", "name":"BOSNIA AND HERZEGOVINA" },
              { "value":"BOTSWANA", "name":"BOTSWANA" },
              { "value":"BOUVET ISLAND", "name":"BOUVET ISLAND" },
              { "value":"BRAZIL", "name":"BRAZIL" },
              { "value":"BRITISH INDIAN OCEAN TERRITORY", "name":"BRITISH INDIAN OCEAN TERRITORY" },
              { "value":"BRUNEI DARUSSALAM", "name":"BRUNEI DARUSSALAM" },
              { "value":"BULGARIA", "name":"BULGARIA" },
              { "value":"BURKINA FASO", "name":"BURKINA FASO" },
              { "value":"BURUNDI", "name":"BURUNDI" },
              { "value":"CAMBODIA", "name":"CAMBODIA" },
              { "value":"CAMEROON", "name":"CAMEROON" },
              { "value":"CAPE VERDE", "name":"CAPE VERDE" },
              { "value":"CAYMAN ISLANDS", "name":"CAYMAN ISLANDS" },
              { "value":"CENTRAL AFRICAN REPUBLIC", "name":"CENTRAL AFRICAN REPUBLIC" },
              { "value":"CHAD", "name":"CHAD" },
              { "value":"CHILE", "name":"CHILE" },
              { "value":"CHINA", "name":"CHINA" },
              { "value":"CHRISTMAS ISLAND", "name":"CHRISTMAS ISLAND" },
              { "value":"COCOS (KEELING) ISLANDS", "name":"COCOS (KEELING) ISLANDS" },
              { "value":"COLOMBIA", "name":"COLOMBIA" },
              { "value":"COMOROS", "name":"COMOROS" },
              { "value":"CONGO", "name":"CONGO" },
              { "value":"CONGO DEMOCRATIC REPUBLIC", "name":"CONGO DEMOCRATIC REPUBLIC" },
              { "value":"COOK ISLANDS", "name":"COOK ISLANDS" },
              { "value":"COSTA RICA", "name":"COSTA RICA" },
              { "value":"COTE D'IVOIRE ", "name":"COTE D'IVOIRE" },
              { "value":"CROATIA", "name":"CROATIA" },
              { "value":"CYPRUS", "name":"CYPRUS" },
              { "value":"CZECH REPUBLIC", "name":"CZECH REPUBLIC" },
              { "value":"DENMARK", "name":"DENMARK" },
              { "value":"DJIBOUTI", "name":"DJIBOUTI" },
              { "value":"DOMINICA", "name":"DOMINICA" },
              { "value":"DOMINICAN REPUBLIC", "name":"DOMINICAN REPUBLIC" },
              { "value":"ECUADOR", "name":"ECUADOR" },
              { "value":"EGYPT", "name":"EGYPT" },
              { "value":"EL SALVADOR", "name":"EL SALVADOR" },
              { "value":"EQUATORIAL GUINEA", "name":"EQUATORIAL GUINEA" },
              { "value":"ERITREA", "name":"ERITREA" },
              { "value":"ESTONIA", "name":"ESTONIA" },
              { "value":"ETHIOPIA", "name":"ETHIOPIA" },
              { "value":"FALKLAND ISLANDS (MALVINAS)", "name":"FALKLAND ISLANDS (MALVINAS)" },
              { "value":"FAROE ISLANDS", "name":"FAROE ISLANDS" },
              { "value":"FIJI", "name":"FIJI" },
              { "value":"FINLAND", "name":"FINLAND" },
              { "value":"FRENCH GUIANA", "name":"FRENCH GUIANA" },
              { "value":"FRENCH POLYNESIA", "name":"FRENCH POLYNESIA" },
              { "value":"FRENCH SOUTHERN TERRITORIES", "name":"FRENCH SOUTHERN TERRITORIES" },
              { "value":"GABON", "name":"GABON" },
              { "value":"GAMBIA", "name":"GAMBIA" },
              { "value":"GEORGIA", "name":"GEORGIA" },
              { "value":"GHANA", "name":"GHANA" },
              { "value":"GIBRALTAR", "name":"GIBRALTAR" },
              { "value":"GREECE", "name":"GREECE" },
              { "value":"GREENLAND", "name":"GREENLAND" },
              { "value":"GRENADA", "name":"GRENADA" },
              { "value":"GUADELOUPE", "name":"GUADELOUPE" },
              { "value":"GUAM", "name":"GUAM" },
              { "value":"GUATEMALA", "name":"GUATEMALA" },
              { "value":"GUERNSEY", "name":"GUERNSEY" },
              { "value":"GUINEA", "name":"GUINEA" },
              { "value":"GUINEA-BISSAU", "name":"GUINEA-BISSAU" },
              { "value":"GUYANA", "name":"GUYANA" },
              { "value":"HAITI", "name":"HAITI" },
              { "value":"HEARD ISLAND AND MCDONALD ISLANDS", "name":"HEARD ISLAND AND MCDONALD ISLANDS" },
              { "value":"HOLY SEE (VATICAN CITY STATE)", "name":"HOLY SEE (VATICAN CITY STATE)" },
              { "value":"HONDURAS", "name":"HONDURAS" },
              { "value":"HONG KONG", "name":"HONG KONG" },
              { "value":"HUNGARY", "name":"HUNGARY" },
              { "value":"ICELAND", "name":"ICELAND" },
              { "value":"INDIA", "name":"INDIA" },
              { "value":"INDONESIA", "name":"INDONESIA" },
              { "value":"IRAQ", "name":"IRAQ" },
              { "value":"IRELAND", "name":"IRELAND" },
              { "value":"ISLE OF MAN", "name":"ISLE OF MAN" },
              { "value":"ISRAEL", "name":"ISRAEL" },
              { "value":"ITALY", "name":"ITALY" },
              { "value":"JAMAICA", "name":"JAMAICA" },
              { "value":"JERSEY", "name":"JERSEY" },
              { "value":"JORDAN", "name":"JORDAN" },
              { "value":"KAZAKHSTAN", "name":"KAZAKHSTAN" },
              { "value":"KENYA", "name":"KENYA" },
              { "value":"KIRIBATI", "name":"KIRIBATI" },
              { "value":"KUWAIT", "name":"KUWAIT" },
              { "value":"KYRGYZSTAN", "name":"KYRGYZSTAN" },
              { "value":"LAO", "name":"LAO" },
              { "value":"LATVIA", "name":"LATVIA" },
              { "value":"LEBANON", "name":"LEBANON" },
              { "value":"LESOTHO", "name":"LESOTHO" },
              { "value":"LIBERIA", "name":"LIBERIA" },
              { "value":"LIBYAN ARAB JAMAHIRIYA", "name":"LIBYAN ARAB JAMAHIRIYA" },
              { "value":"LIECHTENSTEIN", "name":"LIECHTENSTEIN" },
              { "value":"LITHUANIA", "name":"LITHUANIA" },
              { "value":"LUXEMBOURG", "name":"LUXEMBOURG" },
              { "value":"MACAO", "name":"MACAO" },
              { "value":"MACEDONIA", "name":"MACEDONIA" },
              { "value":"MADAGASCAR", "name":"MADAGASCAR" },
              { "value":"MALAWI", "name":"MALAWI" },
              { "value":"MALAYSIA", "name":"MALAYSIA" },
              { "value":"MALDIVES", "name":"MALDIVES" },
              { "value":"MALI", "name":"MALI" },
              { "value":"MALTA", "name":"MALTA" },
              { "value":"MARSHALL ISLANDS", "name":"MARSHALL ISLANDS" },
              { "value":"MARTINIQUE", "name":"MARTINIQUE" },
              { "value":"MAURITANIA", "name":"MAURITANIA" },
              { "value":"MAURITIUS", "name":"MAURITIUS" },
              { "value":"MAYOTTE", "name":"MAYOTTE" },
              { "value":"MEXICO", "name":"MEXICO" },
              { "value":"MICRONESIA FEDERATED STATES", "name":"MICRONESIA FEDERATED STATES" },
              { "value":"MOLDOVA", "name":"MOLDOVA" },
              { "value":"MONACO", "name":"MONACO" },
              { "value":"MONGOLIA", "name":"MONGOLIA" },
              { "value":"MONTENEGRO", "name":"MONTENEGRO" },
              { "value":"MONTSERRAT", "name":"MONTSERRAT" },
              { "value":"MOROCCO", "name":"MOROCCO" },
              { "value":"MOZAMBIQUE", "name":"MOZAMBIQUE" },
              { "value":"MYANMAR", "name":"MYANMAR" },
              { "value":"NAMIBIA", "name":"NAMIBIA" },
              { "value":"NAURU", "name":"NAURU" },
              { "value":"NEPAL", "name":"NEPAL" },
              { "value":"NETHERLANDS ANTILLES", "name":"NETHERLANDS ANTILLES" },
              { "value":"NEW CALEDONIA", "name":"NEW CALEDONIA" },
              { "value":"NEW ZEALAND", "name":"NEW ZEALAND" },
              { "value":"NICARAGUA", "name":"NICARAGUA" },
              { "value":"NIGER", "name":"NIGER" },
              { "value":"NIGERIA", "name":"NIGERIA" },
              { "value":"NIUE", "name":"NIUE" },
              { "value":"NORFOLK ISLAND", "name":"NORFOLK ISLAND" },
              { "value":"NORTHERN MARIANA ISLANDS", "name":"NORTHERN MARIANA ISLANDS" },
              { "value":"NORWAY", "name":"NORWAY" },
              { "value":"OMAN", "name":"OMAN" },
              { "value":"PAKISTAN", "name":"PAKISTAN" },
              { "value":"PALAU", "name":"PALAU" },
              { "value":"PALESTINIAN TERRITORY OCCUPIED", "name":"PALESTINIAN TERRITORY OCCUPIED" },
              { "value":"PANAMA", "name":"PANAMA" },
              { "value":"PAPUA NEW GUINEA", "name":"PAPUA NEW GUINEA" },
              { "value":"PARAGUAY", "name":"PARAGUAY" },
              { "value":"PERU", "name":"PERU" },
              { "value":"PHILIPPINES", "name":"PHILIPPINES" },
              { "value":"PITCAIRN", "name":"PITCAIRN" },
              { "value":"POLAND", "name":"POLAND" },
              { "value":"PORTUGAL", "name":"PORTUGAL" },
              { "value":"PUERTO RICO", "name":"PUERTO RICO" },
              { "value":"QATAR", "name":"QATAR" },
              { "value":"R?UNION", "name":"R?UNION" },
              { "value":"ROMANIA", "name":"ROMANIA" },
              { "value":"RUSSIAN FEDERATION", "name":"RUSSIAN FEDERATION" },
              { "value":"RWANDA", "name":"RWANDA" },
              { "value":"SAINT BARTH?LEMY", "name":"SAINT BARTH?LEMY" },
              { "value":"SAINT HELENA ASCENSION AND TRISTAN DA CUNHA", "name":"SAINT HELENA ASCENSION AND TRISTAN DA CUNHA" },
              { "value":"SAINT KITTS AND NEVIS", "name":"SAINT KITTS AND NEVIS" },
              { "value":"SAINT LUCIA", "name":"SAINT LUCIA" },
              { "value":"SAINT MARTIN", "name":"SAINT MARTIN" },
              { "value":"SAINT PIERRE AND MIQUELON", "name":"SAINT PIERRE AND MIQUELON" },
              { "value":"SAINT VINCENT AND THE GRENADINES", "name":"SAINT VINCENT AND THE GRENADINES" },
              { "value":"SAMOA", "name":"SAMOA" },
              { "value":"SAN MARINO", "name":"SAN MARINO" },
              { "value":"SAO TOME AND PRINCIPE", "name":"SAO TOME AND PRINCIPE" },
              { "value":"SAUDI ARABIA", "name":"SAUDI ARABIA" },
              { "value":"SENEGAL", "name":"SENEGAL" },
              { "value":"SERBIA", "name":"SERBIA" },
              { "value":"SEYCHELLES", "name":"SEYCHELLES" },
              { "value":"SIERRA LEONE", "name":"SIERRA LEONE" },
              { "value":"SINGAPORE", "name":"SINGAPORE" },
              { "value":"SLOVAKIA", "name":"SLOVAKIA" },
              { "value":"SLOVENIA", "name":"SLOVENIA" },
              { "value":"SOLOMON ISLANDS", "name":"SOLOMON ISLANDS" },
              { "value":"SOMALIA", "name":"SOMALIA" },
              { "value":"SOUTH AFRICA", "name":"SOUTH AFRICA" },
              { "value":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "name":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS" },
              { "value":"SPAIN", "name":"SPAIN" },
              { "value":"SRI LANKA", "name":"SRI LANKA" },
              { "value":"SURINAME", "name":"SURINAME" },
              { "value":"SVALBARD AND JAN MAYEN", "name":"SVALBARD AND JAN MAYEN" },
              { "value":"SWAZILAND", "name":"SWAZILAND" },
              { "value":"TAIWAN", "name":"TAIWAN" },
              { "value":"TAJIKISTAN", "name":"TAJIKISTAN" },
              { "value":"TANZANIA", "name":"TANZANIA" },
              { "value":"THAILAND", "name":"THAILAND" },
              { "value":"TIMOR-LESTE", "name":"TIMOR-LESTE" },
              { "value":"TOGO", "name":"TOGO" },
              { "value":"TOKELAU", "name":"TOKELAU" },
              { "value":"TONGA", "name":"TONGA" },
              { "value":"TRINIDAD AND TOBAGO", "name":"TRINIDAD AND TOBAGO" },
              { "value":"TUNISIA", "name":"TUNISIA" },
              { "value":"TURKEY", "name":"TURKEY" },
              { "value":"TURKMENISTAN", "name":"TURKMENISTAN" },
              { "value":"TURKS AND CAICOS ISLANDS", "name":"TURKS AND CAICOS ISLANDS" },
              { "value":"TUVALU", "name":"TUVALU" },
              { "value":"UGANDA", "name":"UGANDA" },
              { "value":"UKRAINE", "name":"UKRAINE" },
              { "value":"UNITED ARAB EMIRATES", "name":"UNITED ARAB EMIRATES" },
              { "value":"URUGUAY", "name":"URUGUAY" },
              { "value":"UZBEKISTAN", "name":"UZBEKISTAN" },
              { "value":"VANUATU", "name":"VANUATU" },
              { "value":"VENEZUELA", "name":"VENEZUELA" },
              { "value":"VIET NAM", "name":"VIET NAM" },
              { "value":"VIRGIN ISLANDS BRITISH", "name":"VIRGIN ISLANDS BRITISH" },
              { "value":"VIRGIN ISLANDS U.S.", "name":"VIRGIN ISLANDS U.S." },
              { "value":"WALLIS AND FUTUNA", "name":"WALLIS AND FUTUNA" },
              { "value":"WESTERN SAHARA", "name":"WESTERN SAHARA" },
              { "value":"YEMEN", "name":"YEMEN" },
              { "value":"ZAMBIA", "name":"ZAMBIA" },
              { "value":"ZIMBABWE", "name":"ZIMBABWE" }
          ],
          storeId: 'usCountryStore'
      });
  }

  connectedCallback() {
  //  <ext-textfield  extname="phone"  label="Phone"  required="true" placeholder="Enter your phone" ></ext-textfield>
      this.innerHTML = `<ext-comboboxfield
                          extname="country"
                          name="country"
                          queryMode="local"
                          displayField="name"
                          valueField="value"
                          forceSelection="true"
                          triggerAction="all"
                          required="true"
                          placeholder="Select Country*"
                          xrequiredMessage="Choose your Country"
                          xautoFocus="false"
                          store="usCountryStore"/>`;

      this._addListeners();
  }

  _addListeners() {
      let comboEl = this.querySelector("ext-comboboxfield");
      comboEl.addEventListener('change', (sender, newValue, oldValue) => {
          var changeEvent = new Event('change');
          changeEvent['country'] = this.getValue();
          this.dispatchEvent(changeEvent);
      });
  }

  getValue() {
      let fieldEl = this.querySelector('ext-comboboxfield');
      return fieldEl.cmp.getValue();
  }

}
window.customElements.define('sencha-field-country', FieldCountryUs);