export function osStore() {
  Ext.create('Ext.data.Store', {
    fields: [ 'text' ],
    data: [
            { "text":"Windows 32-bit" },
            { "text":"Windows 64-bit" },
            { "text":"Linux 32-bit" },
            { "text":"Linux 64-bit" },
            { "text":"Mac OS X" }
    ],
    storeId: 'osStore'
  });
}

export function usCountryStore() {
  Ext.create('Ext.data.Store', {
    fields: [ 'name', 'value' ],
    data: [
        { "text":"UNITED STATES" },
        { "value":"CANADA", "text":"CANADA" },
        { "value":"UNITED KINGDOM", "text":"UNITED KINGDOM" },
        { "value":"GERMANY", "text":"GERMANY" },
        { "value":"FRANCE", "text":"FRANCE" },
        { "value":"NETHERLANDS", "text":"NETHERLANDS" },
        { "value":"SWEDEN", "text":"SWEDEN" },
        { "value":"SWITZERLAND", "text":"SWITZERLAND" },
        { "value":"JAPAN", "text":"JAPAN" },
        { "value":"SOUTH KOREA", "text":"SOUTH KOREA" },
        { "value":"AUSTRALIA", "text":"AUSTRALIA" },
        { "value":"AFGHANISTAN", "text":"AFGHANISTAN" },
        { "value":"ALAND ISLANDS", "text":"ALAND ISLANDS" },
        { "value":"ALBANIA", "text":"ALBANIA" },
        { "value":"ALGERIA", "text":"ALGERIA" },
        { "value":"AMERICAN SAMOA", "text":"AMERICAN SAMOA" },
        { "value":"ANDORRA", "text":"ANDORRA" },
        { "value":"ANGOLA", "text":"ANGOLA" },
        { "value":"ANGUILLA", "text":"ANGUILLA" },
        { "value":"ANTARCTICA", "text":"ANTARCTICA" },
        { "value":"ANTIGUA AND BARBUDA", "text":"ANTIGUA AND BARBUDA" },
        { "value":"ARGENTINA", "text":"ARGENTINA" },
        { "value":"ARMENIA", "text":"ARMENIA" },
        { "value":"ARUBA", "text":"ARUBA" },
        { "value":"AUSTRIA", "text":"AUSTRIA" },
        { "value":"AZERBAIJAN", "text":"AZERBAIJAN" },
        { "value":"BAHAMAS", "text":"BAHAMAS" },
        { "value":"BAHRAIN", "text":"BAHRAIN" },
        { "value":"BANGLADESH", "text":"BANGLADESH" },
        { "value":"BARBADOS", "text":"BARBADOS" },
        { "value":"BELARUS", "text":"BELARUS" },
        { "value":"BELGIUM", "text":"BELGIUM" },
        { "value":"BELIZE", "text":"BELIZE" },
        { "value":"BENIN", "text":"BENIN" },
        { "value":"BERMUDA", "text":"BERMUDA" },
        { "value":"BHUTAN", "text":"BHUTAN" },
        { "value":"BOLIVIA", "text":"BOLIVIA" },
        { "value":"BOSNIA AND HERZEGOVINA", "text":"BOSNIA AND HERZEGOVINA" },
        { "value":"BOTSWANA", "text":"BOTSWANA" },
        { "value":"BOUVET ISLAND", "text":"BOUVET ISLAND" },
        { "value":"BRAZIL", "text":"BRAZIL" },
        { "value":"BRITISH INDIAN OCEAN TERRITORY", "text":"BRITISH INDIAN OCEAN TERRITORY" },
        { "value":"BRUNEI DARUSSALAM", "text":"BRUNEI DARUSSALAM" },
        { "value":"BULGARIA", "text":"BULGARIA" },
        { "value":"BURKINA FASO", "text":"BURKINA FASO" },
        { "value":"BURUNDI", "text":"BURUNDI" },
        { "value":"CAMBODIA", "text":"CAMBODIA" },
        { "value":"CAMEROON", "text":"CAMEROON" },
        { "value":"CAPE VERDE", "text":"CAPE VERDE" },
        { "value":"CAYMAN ISLANDS", "text":"CAYMAN ISLANDS" },
        { "value":"CENTRAL AFRICAN REPUBLIC", "text":"CENTRAL AFRICAN REPUBLIC" },
        { "value":"CHAD", "text":"CHAD" },
        { "value":"CHILE", "text":"CHILE" },
        { "value":"CHINA", "text":"CHINA" },
        { "value":"CHRISTMAS ISLAND", "text":"CHRISTMAS ISLAND" },
        { "value":"COCOS (KEELING) ISLANDS", "text":"COCOS (KEELING) ISLANDS" },
        { "value":"COLOMBIA", "text":"COLOMBIA" },
        { "value":"COMOROS", "text":"COMOROS" },
        { "value":"CONGO", "text":"CONGO" },
        { "value":"CONGO DEMOCRATIC REPUBLIC", "text":"CONGO DEMOCRATIC REPUBLIC" },
        { "value":"COOK ISLANDS", "text":"COOK ISLANDS" },
        { "value":"COSTA RICA", "text":"COSTA RICA" },
        { "value":"COTE D'IVOIRE ", "text":"COTE D'IVOIRE" },
        { "value":"CROATIA", "text":"CROATIA" },
        { "value":"CYPRUS", "text":"CYPRUS" },
        { "value":"CZECH REPUBLIC", "text":"CZECH REPUBLIC" },
        { "value":"DENMARK", "text":"DENMARK" },
        { "value":"DJIBOUTI", "text":"DJIBOUTI" },
        { "value":"DOMINICA", "text":"DOMINICA" },
        { "value":"DOMINICAN REPUBLIC", "text":"DOMINICAN REPUBLIC" },
        { "value":"ECUADOR", "text":"ECUADOR" },
        { "value":"EGYPT", "text":"EGYPT" },
        { "value":"EL SALVADOR", "text":"EL SALVADOR" },
        { "value":"EQUATORIAL GUINEA", "text":"EQUATORIAL GUINEA" },
        { "value":"ERITREA", "text":"ERITREA" },
        { "value":"ESTONIA", "text":"ESTONIA" },
        { "value":"ETHIOPIA", "text":"ETHIOPIA" },
        { "value":"FALKLAND ISLANDS (MALVINAS)", "text":"FALKLAND ISLANDS (MALVINAS)" },
        { "value":"FAROE ISLANDS", "text":"FAROE ISLANDS" },
        { "value":"FIJI", "text":"FIJI" },
        { "value":"FINLAND", "text":"FINLAND" },
        { "value":"FRENCH GUIANA", "text":"FRENCH GUIANA" },
        { "value":"FRENCH POLYNESIA", "text":"FRENCH POLYNESIA" },
        { "value":"FRENCH SOUTHERN TERRITORIES", "text":"FRENCH SOUTHERN TERRITORIES" },
        { "value":"GABON", "text":"GABON" },
        { "value":"GAMBIA", "text":"GAMBIA" },
        { "value":"GEORGIA", "text":"GEORGIA" },
        { "value":"GHANA", "text":"GHANA" },
        { "value":"GIBRALTAR", "text":"GIBRALTAR" },
        { "value":"GREECE", "text":"GREECE" },
        { "value":"GREENLAND", "text":"GREENLAND" },
        { "value":"GRENADA", "text":"GRENADA" },
        { "value":"GUADELOUPE", "text":"GUADELOUPE" },
        { "value":"GUAM", "text":"GUAM" },
        { "value":"GUATEMALA", "text":"GUATEMALA" },
        { "value":"GUERNSEY", "text":"GUERNSEY" },
        { "value":"GUINEA", "text":"GUINEA" },
        { "value":"GUINEA-BISSAU", "text":"GUINEA-BISSAU" },
        { "value":"GUYANA", "text":"GUYANA" },
        { "value":"HAITI", "text":"HAITI" },
        { "value":"HEARD ISLAND AND MCDONALD ISLANDS", "text":"HEARD ISLAND AND MCDONALD ISLANDS" },
        { "value":"HOLY SEE (VATICAN CITY STATE)", "text":"HOLY SEE (VATICAN CITY STATE)" },
        { "value":"HONDURAS", "text":"HONDURAS" },
        { "value":"HONG KONG", "text":"HONG KONG" },
        { "value":"HUNGARY", "text":"HUNGARY" },
        { "value":"ICELAND", "text":"ICELAND" },
        { "value":"INDIA", "text":"INDIA" },
        { "value":"INDONESIA", "text":"INDONESIA" },
        { "value":"IRAQ", "text":"IRAQ" },
        { "value":"IRELAND", "text":"IRELAND" },
        { "value":"ISLE OF MAN", "text":"ISLE OF MAN" },
        { "value":"ISRAEL", "text":"ISRAEL" },
        { "value":"ITALY", "text":"ITALY" },
        { "value":"JAMAICA", "text":"JAMAICA" },
        { "value":"JERSEY", "text":"JERSEY" },
        { "value":"JORDAN", "text":"JORDAN" },
        { "value":"KAZAKHSTAN", "text":"KAZAKHSTAN" },
        { "value":"KENYA", "text":"KENYA" },
        { "value":"KIRIBATI", "text":"KIRIBATI" },
        { "value":"KUWAIT", "text":"KUWAIT" },
        { "value":"KYRGYZSTAN", "text":"KYRGYZSTAN" },
        { "value":"LAO", "text":"LAO" },
        { "value":"LATVIA", "text":"LATVIA" },
        { "value":"LEBANON", "text":"LEBANON" },
        { "value":"LESOTHO", "text":"LESOTHO" },
        { "value":"LIBERIA", "text":"LIBERIA" },
        { "value":"LIBYAN ARAB JAMAHIRIYA", "text":"LIBYAN ARAB JAMAHIRIYA" },
        { "value":"LIECHTENSTEIN", "text":"LIECHTENSTEIN" },
        { "value":"LITHUANIA", "text":"LITHUANIA" },
        { "value":"LUXEMBOURG", "text":"LUXEMBOURG" },
        { "value":"MACAO", "text":"MACAO" },
        { "value":"MACEDONIA", "text":"MACEDONIA" },
        { "value":"MADAGASCAR", "text":"MADAGASCAR" },
        { "value":"MALAWI", "text":"MALAWI" },
        { "value":"MALAYSIA", "text":"MALAYSIA" },
        { "value":"MALDIVES", "text":"MALDIVES" },
        { "value":"MALI", "text":"MALI" },
        { "value":"MALTA", "text":"MALTA" },
        { "value":"MARSHALL ISLANDS", "text":"MARSHALL ISLANDS" },
        { "value":"MARTINIQUE", "text":"MARTINIQUE" },
        { "value":"MAURITANIA", "text":"MAURITANIA" },
        { "value":"MAURITIUS", "text":"MAURITIUS" },
        { "value":"MAYOTTE", "text":"MAYOTTE" },
        { "value":"MEXICO", "text":"MEXICO" },
        { "value":"MICRONESIA FEDERATED STATES", "text":"MICRONESIA FEDERATED STATES" },
        { "value":"MOLDOVA", "text":"MOLDOVA" },
        { "value":"MONACO", "text":"MONACO" },
        { "value":"MONGOLIA", "text":"MONGOLIA" },
        { "value":"MONTENEGRO", "text":"MONTENEGRO" },
        { "value":"MONTSERRAT", "text":"MONTSERRAT" },
        { "value":"MOROCCO", "text":"MOROCCO" },
        { "value":"MOZAMBIQUE", "text":"MOZAMBIQUE" },
        { "value":"MYANMAR", "text":"MYANMAR" },
        { "value":"NAMIBIA", "text":"NAMIBIA" },
        { "value":"NAURU", "text":"NAURU" },
        { "value":"NEPAL", "text":"NEPAL" },
        { "value":"NETHERLANDS ANTILLES", "text":"NETHERLANDS ANTILLES" },
        { "value":"NEW CALEDONIA", "text":"NEW CALEDONIA" },
        { "value":"NEW ZEALAND", "text":"NEW ZEALAND" },
        { "value":"NICARAGUA", "text":"NICARAGUA" },
        { "value":"NIGER", "text":"NIGER" },
        { "value":"NIGERIA", "text":"NIGERIA" },
        { "value":"NIUE", "text":"NIUE" },
        { "value":"NORFOLK ISLAND", "text":"NORFOLK ISLAND" },
        { "value":"NORTHERN MARIANA ISLANDS", "text":"NORTHERN MARIANA ISLANDS" },
        { "value":"NORWAY", "text":"NORWAY" },
        { "value":"OMAN", "text":"OMAN" },
        { "value":"PAKISTAN", "text":"PAKISTAN" },
        { "value":"PALAU", "text":"PALAU" },
        { "value":"PALESTINIAN TERRITORY OCCUPIED", "text":"PALESTINIAN TERRITORY OCCUPIED" },
        { "value":"PANAMA", "text":"PANAMA" },
        { "value":"PAPUA NEW GUINEA", "text":"PAPUA NEW GUINEA" },
        { "value":"PARAGUAY", "text":"PARAGUAY" },
        { "value":"PERU", "text":"PERU" },
        { "value":"PHILIPPINES", "text":"PHILIPPINES" },
        { "value":"PITCAIRN", "text":"PITCAIRN" },
        { "value":"POLAND", "text":"POLAND" },
        { "value":"PORTUGAL", "text":"PORTUGAL" },
        { "value":"PUERTO RICO", "text":"PUERTO RICO" },
        { "value":"QATAR", "text":"QATAR" },
        { "value":"R?UNION", "text":"R?UNION" },
        { "value":"ROMANIA", "text":"ROMANIA" },
        { "value":"RUSSIAN FEDERATION", "text":"RUSSIAN FEDERATION" },
        { "value":"RWANDA", "text":"RWANDA" },
        { "value":"SAINT BARTH?LEMY", "text":"SAINT BARTH?LEMY" },
        { "value":"SAINT HELENA ASCENSION AND TRISTAN DA CUNHA", "text":"SAINT HELENA ASCENSION AND TRISTAN DA CUNHA" },
        { "value":"SAINT KITTS AND NEVIS", "text":"SAINT KITTS AND NEVIS" },
        { "value":"SAINT LUCIA", "text":"SAINT LUCIA" },
        { "value":"SAINT MARTIN", "text":"SAINT MARTIN" },
        { "value":"SAINT PIERRE AND MIQUELON", "text":"SAINT PIERRE AND MIQUELON" },
        { "value":"SAINT VINCENT AND THE GRENADINES", "text":"SAINT VINCENT AND THE GRENADINES" },
        { "value":"SAMOA", "text":"SAMOA" },
        { "value":"SAN MARINO", "text":"SAN MARINO" },
        { "value":"SAO TOME AND PRINCIPE", "text":"SAO TOME AND PRINCIPE" },
        { "value":"SAUDI ARABIA", "text":"SAUDI ARABIA" },
        { "value":"SENEGAL", "text":"SENEGAL" },
        { "value":"SERBIA", "text":"SERBIA" },
        { "value":"SEYCHELLES", "text":"SEYCHELLES" },
        { "value":"SIERRA LEONE", "text":"SIERRA LEONE" },
        { "value":"SINGAPORE", "text":"SINGAPORE" },
        { "value":"SLOVAKIA", "text":"SLOVAKIA" },
        { "value":"SLOVENIA", "text":"SLOVENIA" },
        { "value":"SOLOMON ISLANDS", "text":"SOLOMON ISLANDS" },
        { "value":"SOMALIA", "text":"SOMALIA" },
        { "value":"SOUTH AFRICA", "text":"SOUTH AFRICA" },
        { "value":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS", "text":"SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS" },
        { "value":"SPAIN", "text":"SPAIN" },
        { "value":"SRI LANKA", "text":"SRI LANKA" },
        { "value":"SURINAME", "text":"SURINAME" },
        { "value":"SVALBARD AND JAN MAYEN", "text":"SVALBARD AND JAN MAYEN" },
        { "value":"SWAZILAND", "text":"SWAZILAND" },
        { "value":"TAIWAN", "text":"TAIWAN" },
        { "value":"TAJIKISTAN", "text":"TAJIKISTAN" },
        { "value":"TANZANIA", "text":"TANZANIA" },
        { "value":"THAILAND", "text":"THAILAND" },
        { "value":"TIMOR-LESTE", "text":"TIMOR-LESTE" },
        { "value":"TOGO", "text":"TOGO" },
        { "value":"TOKELAU", "text":"TOKELAU" },
        { "value":"TONGA", "text":"TONGA" },
        { "value":"TRINIDAD AND TOBAGO", "text":"TRINIDAD AND TOBAGO" },
        { "value":"TUNISIA", "text":"TUNISIA" },
        { "value":"TURKEY", "text":"TURKEY" },
        { "value":"TURKMENISTAN", "text":"TURKMENISTAN" },
        { "value":"TURKS AND CAICOS ISLANDS", "text":"TURKS AND CAICOS ISLANDS" },
        { "value":"TUVALU", "text":"TUVALU" },
        { "value":"UGANDA", "text":"UGANDA" },
        { "value":"UKRAINE", "text":"UKRAINE" },
        { "value":"UNITED ARAB EMIRATES", "text":"UNITED ARAB EMIRATES" },
        { "value":"URUGUAY", "text":"URUGUAY" },
        { "value":"UZBEKISTAN", "text":"UZBEKISTAN" },
        { "value":"VANUATU", "text":"VANUATU" },
        { "value":"VENEZUELA", "text":"VENEZUELA" },
        { "value":"VIET NAM", "text":"VIET NAM" },
        { "value":"VIRGIN ISLANDS BRITISH", "text":"VIRGIN ISLANDS BRITISH" },
        { "value":"VIRGIN ISLANDS U.S.", "text":"VIRGIN ISLANDS U.S." },
        { "value":"WALLIS AND FUTUNA", "text":"WALLIS AND FUTUNA" },
        { "value":"WESTERN SAHARA", "text":"WESTERN SAHARA" },
        { "value":"YEMEN", "text":"YEMEN" },
        { "value":"ZAMBIA", "text":"ZAMBIA" },
        { "value":"ZIMBABWE", "text":"ZIMBABWE" }
    ],
    storeId: 'usCountryStore'
});
}

export function usStateStore() {
  Ext.create('Ext.data.Store', {
    fields: [ 'name', 'value' ],
    data: [
        { "value":"AL","text":"Alabama" },
        { "value":"AK","text":"Alaska" },
        { "value":"AS","text":"American Samoa" },
        { "value":"AZ","text":"Arizona" },
        { "value":"CA","text":"California" },
        { "value":"CO","text":"Colorado" },
        { "value":"CT","text":"Connecticut" },
        { "value":"DE","text":"Delaware" },
        { "value":"DC","text":"District of Columbia" },
        { "value":"FL","text":"Florida" },
        { "value":"GA","text":"Georgia" },
        { "value":"GU","text":"Guam" },
        { "value":"HI","text":"Hawaii" },
        { "value":"ID","text":"Idaho" },
        { "value":"IL","text":"Illinois" },
        { "value":"IN","text":"Indiana" },
        { "value":"IA","text":"Iowa" },
        { "value":"KS","text":"Kansas" },
        { "value":"KY","text":"Kentucky" },
        { "value":"LA","text":"Louisiana" },
        { "value":"ME","text":"Maine" },
        { "value":"MD","text":"Maryland" },
        { "value":"MH","text":"Marshall Islands" },
        { "value":"MA","text":"Massachusetts" },
        { "value":"MI","text":"Michigan" },
        { "value":"MN","text":"Minnesota" },
        { "value":"MS","text":"Mississippi" },
        { "value":"MO","text":"Missouri" },
        { "value":"MT","text":"Montana" },
        { "value":"NE","text":"Nebraska" },
        { "value":"NV","text":"Nevada" },
        { "value":"NH","text":"New Hampshire" },
        { "value":"NJ","text":"New Jersey" },
        { "value":"NM","text":"New Mexico" },
        { "value":"NY","text":"New York" },
        { "value":"NC","text":"North Carolina" },
        { "value":"ND","text":"North Dakota" },
        { "value":"OH","text":"Ohio" },
        { "value":"OK","text":"Oklahoma" },
        { "value":"OR","text":"Oregon" },
        { "value":"PW","text":"Palau" },
        { "value":"PA","text":"Pennsylvania" },
        { "value":"PR","text":"Puerto Rico" },
        { "value":"RI","text":"Rhode Island" },
        { "value":"SC","text":"South Carolina" },
        { "value":"SD","text":"South Dakota" },
        { "value":"TN","text":"Tennessee" },
        { "value":"TX","text":"Texas" },
        { "value":"UT","text":"Utah" },
        { "value":"VT","text":"Vermont" },
        { "value":"VI","text":"Virgin Islands" },
        { "value":"VA","text":"Virginia" },
        { "value":"WA","text":"Washington" },
        { "value":"WV","text":"West Virginia" },
        { "value":"WI","text":"Wisconsin" },
        { "value":"WY","text":"Wyoming" },
        { "value":"AE","text":"Armed Forces AE" },
        { "value":"AP","text":"Armed Forces AP" }
    ],
    storeId: 'usStateStore'
});
}

export function caProvinceStore() {

  Ext.create('Ext.data.Store', {
    fields: [ 'name', 'value' ],
    data: [
        { "value":"AB","text":"Alberta" },
        { "value":"BC","text":"British Columbia" },
        { "value":"MB","text":"Manitoba" },
        { "value":"NB","text":"New Brunswick" },
        { "value":"NF","text":"Newfoundland" },
        { "value":"NT","text":"Northwest Terr." },
        { "value":"NS","text":"Nova Scotia" },
        { "value":"NU","text":"Nunavut" },
        { "value":"ON","text":"Ontario" },
        { "value":"PE","text":"Prince Edward Island" },
        { "value":"QC","text":"Quebec" },
        { "value":"SK","text":"Saskatchewan" },
        { "value":"YT","text":"Yukon" }
    ],
    storeId: 'caProvinceStore'
});
}

export function mxStateStore() {
  Ext.create('Ext.data.Store', {
    fields: [ 'name', 'value' ],
    data: [
        { "value":"AG","text":"Aguascalientes" },
        { "value":"BC","text":"Baja California" },
        { "value":"BS","text":"Baja California Sur" },
        { "value":"CM","text":"Campeche" },
        { "value":"CS","text":"Chiapas" },
        { "value":"CH","text":"Chihuahua" },
        { "value":"CO","text":"Coahuila" },
        { "value":"CL","text":"Colima" },
        { "value":"DF","text":"Distrito Federal" },
        { "value":"DG","text":"Durango" },
        { "value":"GT","text":"Guanajuanto" },
        { "value":"GR","text":"Guerrero" },
        { "value":"HG","text":"Hidalgo" },
        { "value":"JA","text":"Jalisco" },
        { "value":"MX","text":"Mexico" },
        { "value":"MI","text":"Michoacan" },
        { "value":"MO","text":"Morelos" },
        { "value":"NA","text":"Nayarit" },
        { "value":"NL","text":"Nuevo Leon" },
        { "value":"OA","text":"Oaxaca" },
        { "value":"PU","text":"Puebla" },
        { "value":"QT","text":"Queretaro" },
        { "value":"QR","text":"Quintana Roo" },
        { "value":"SL","text":"San Luis Potosi" },
        { "value":"SI","text":"Sinaloa" },
        { "value":"SO","text":"Sonora" },
        { "value":"TB","text":"Tabasco" },
        { "value":"TM","text":"Tamaulipas" },
        { "value":"TL","text":"Tlaxcala" },
        { "value":"VE","text":"Veracruz" },
        { "value":"YU","text":"Yucatan" },
        { "value":"ZA","text":"Zacatecas" }
    ],
    storeId: 'mxStateStore'
});
}

export function brStateStore() {
  Ext.create('Ext.data.Store', {
    fields: [ 'name', 'value' ],
    data: [
            { "value":"AC","text":"Acre" },
            { "value":"AL","text":"Alagoas" },
            { "value":"AP","text":"Amapá" },
            { "value":"AM","text":"Amazonas" },
            { "value":"BA","text":"Bahia" },
            { "value":"CE","text":"Ceará" },
            { "value":"DF","text":"Distrito Federal" },
            { "value":"ES","text":"Espírito Santo" },
            { "value":"GO","text":"Goiás" },
            { "value":"MA","text":"Maranhão" },
            { "value":"MT","text":"Mato Grosso" },
            { "value":"MS","text":"Mato Grosso do Sul" },
            { "value":"MG","text":"Minas Gerais" },
            { "value":"PA","text":"Pará" },
            { "value":"PB","text":"Paraíba" },
            { "value":"PR","text":"Paraná" },
            { "value":"PE","text":"Pernambuco" },
            { "value":"PI","text":"Piauí" },
            { "value":"RJ","text":"Rio de Janeiro" },
            { "value":"RN","text":"Rio Grande do Norte" },
            { "value":"RS","text":"Rio Grande do Sul" },
            { "value":"RO","text":"Rondônia" },
            { "value":"RR","text":"Rorâima" },
            { "value":"SC","text":"Santa Catarina" },
            { "value":"SP","text":"São Paulo" },
            { "value":"SE","text":"Sergipe" },
            { "value":"TO","text":"Tocantins" }
    ],
    storeId: 'brStateStore'
});
}